# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created: Sun Mar  1 16:03:50 2015
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(923, 936)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.tab)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.buttonOpenFile = QtGui.QPushButton(self.tab)
        self.buttonOpenFile.setObjectName(_fromUtf8("buttonOpenFile"))
        self.verticalLayout_3.addWidget(self.buttonOpenFile)
        self.buttonImportFolder = QtGui.QPushButton(self.tab)
        self.buttonImportFolder.setObjectName(_fromUtf8("buttonImportFolder"))
        self.verticalLayout_3.addWidget(self.buttonImportFolder)
        self.listWidgetFileListing = QtGui.QListWidget(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidgetFileListing.sizePolicy().hasHeightForWidth())
        self.listWidgetFileListing.setSizePolicy(sizePolicy)
        self.listWidgetFileListing.setMinimumSize(QtCore.QSize(171, 0))
        self.listWidgetFileListing.setDragEnabled(True)
        self.listWidgetFileListing.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.listWidgetFileListing.setIconSize(QtCore.QSize(35, 35))
        self.listWidgetFileListing.setTextElideMode(QtCore.Qt.ElideLeft)
        self.listWidgetFileListing.setMovement(QtGui.QListView.Static)
        self.listWidgetFileListing.setResizeMode(QtGui.QListView.Adjust)
        self.listWidgetFileListing.setViewMode(QtGui.QListView.ListMode)
        self.listWidgetFileListing.setWordWrap(True)
        self.listWidgetFileListing.setObjectName(_fromUtf8("listWidgetFileListing"))
        self.verticalLayout_3.addWidget(self.listWidgetFileListing)
        self.buttonClearAll = QtGui.QPushButton(self.tab)
        self.buttonClearAll.setObjectName(_fromUtf8("buttonClearAll"))
        self.verticalLayout_3.addWidget(self.buttonClearAll)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.widget = QtGui.QWidget(self.tab)
        self.widget.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.labelPreviewTitle = QtGui.QLabel(self.widget)
        self.labelPreviewTitle.setText(_fromUtf8(""))
        self.labelPreviewTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPreviewTitle.setObjectName(_fromUtf8("labelPreviewTitle"))
        self.verticalLayout_4.addWidget(self.labelPreviewTitle)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_10 = QtGui.QLabel(self.widget)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_2.addWidget(self.label_10, 0, 3, 1, 1)
        self.label_9 = QtGui.QLabel(self.widget)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 0, 2, 1, 1)
        self.label_7 = QtGui.QLabel(self.widget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 0, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.widget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_2.addWidget(self.label_8, 0, 1, 1, 1)
        self.spinBoxCropTop = QtGui.QSpinBox(self.widget)
        self.spinBoxCropTop.setMaximum(9000)
        self.spinBoxCropTop.setObjectName(_fromUtf8("spinBoxCropTop"))
        self.gridLayout_2.addWidget(self.spinBoxCropTop, 1, 0, 1, 1)
        self.spinBoxCropLeft = QtGui.QSpinBox(self.widget)
        self.spinBoxCropLeft.setMaximum(9000)
        self.spinBoxCropLeft.setObjectName(_fromUtf8("spinBoxCropLeft"))
        self.gridLayout_2.addWidget(self.spinBoxCropLeft, 1, 1, 1, 1)
        self.spinBoxCropBottom = QtGui.QSpinBox(self.widget)
        self.spinBoxCropBottom.setMaximum(9000)
        self.spinBoxCropBottom.setObjectName(_fromUtf8("spinBoxCropBottom"))
        self.gridLayout_2.addWidget(self.spinBoxCropBottom, 1, 2, 1, 1)
        self.spinBoxCropRight = QtGui.QSpinBox(self.widget)
        self.spinBoxCropRight.setMaximum(9000)
        self.spinBoxCropRight.setObjectName(_fromUtf8("spinBoxCropRight"))
        self.gridLayout_2.addWidget(self.spinBoxCropRight, 1, 3, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_2)
        self.phononPlaceholder = QtGui.QFrame(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phononPlaceholder.sizePolicy().hasHeightForWidth())
        self.phononPlaceholder.setSizePolicy(sizePolicy)
        self.phononPlaceholder.setMinimumSize(QtCore.QSize(0, 0))
        self.phononPlaceholder.setStyleSheet(_fromUtf8("background:#303030;"))
        self.phononPlaceholder.setFrameShape(QtGui.QFrame.StyledPanel)
        self.phononPlaceholder.setFrameShadow(QtGui.QFrame.Raised)
        self.phononPlaceholder.setObjectName(_fromUtf8("phononPlaceholder"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.phononPlaceholder)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.phonon = QtGui.QWidget(self.phononPlaceholder)
        self.phonon.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phonon.sizePolicy().hasHeightForWidth())
        self.phonon.setSizePolicy(sizePolicy)
        self.phonon.setObjectName(_fromUtf8("phonon"))
        self.horizontalLayout_5.addWidget(self.phonon)
        self.verticalLayout_4.addWidget(self.phononPlaceholder)
        self.widget_2 = QtGui.QWidget(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 12))
        self.widget_2.setStyleSheet(_fromUtf8("background-color:lightblue;\n"
"margin-right:5px;\n"
"margin-left:5px;"))
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.verticalLayout_4.addWidget(self.widget_2)
        self.horizontalSliderSeek = QtGui.QSlider(self.widget)
        self.horizontalSliderSeek.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderSeek.setInvertedControls(False)
        self.horizontalSliderSeek.setTickPosition(QtGui.QSlider.TicksAbove)
        self.horizontalSliderSeek.setObjectName(_fromUtf8("horizontalSliderSeek"))
        self.verticalLayout_4.addWidget(self.horizontalSliderSeek)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.buttonABmode = QtGui.QPushButton(self.widget)
        self.buttonABmode.setObjectName(_fromUtf8("buttonABmode"))
        self.gridLayout.addWidget(self.buttonABmode, 1, 1, 1, 1)
        self.buttonPlayPause = QtGui.QPushButton(self.widget)
        self.buttonPlayPause.setObjectName(_fromUtf8("buttonPlayPause"))
        self.gridLayout.addWidget(self.buttonPlayPause, 0, 2, 1, 1)
        self.buttonSetStart = QtGui.QPushButton(self.widget)
        self.buttonSetStart.setObjectName(_fromUtf8("buttonSetStart"))
        self.gridLayout.addWidget(self.buttonSetStart, 0, 0, 1, 1)
        self.buttonSetEnd = QtGui.QPushButton(self.widget)
        self.buttonSetEnd.setObjectName(_fromUtf8("buttonSetEnd"))
        self.gridLayout.addWidget(self.buttonSetEnd, 0, 4, 1, 1)
        self.doubleSpinBoxSectionEnd = QtGui.QDoubleSpinBox(self.widget)
        self.doubleSpinBoxSectionEnd.setMaximum(9900.99)
        self.doubleSpinBoxSectionEnd.setObjectName(_fromUtf8("doubleSpinBoxSectionEnd"))
        self.gridLayout.addWidget(self.doubleSpinBoxSectionEnd, 1, 4, 1, 1)
        self.CurrentPosition = QtGui.QLabel(self.widget)
        self.CurrentPosition.setText(_fromUtf8(""))
        self.CurrentPosition.setAlignment(QtCore.Qt.AlignCenter)
        self.CurrentPosition.setObjectName(_fromUtf8("CurrentPosition"))
        self.gridLayout.addWidget(self.CurrentPosition, 1, 2, 1, 1)
        self.doubleSpinBoxSectionStart = QtGui.QDoubleSpinBox(self.widget)
        self.doubleSpinBoxSectionStart.setObjectName(_fromUtf8("doubleSpinBoxSectionStart"))
        self.gridLayout.addWidget(self.doubleSpinBoxSectionStart, 1, 0, 1, 1)
        self.buttonMute = QtGui.QPushButton(self.widget)
        self.buttonMute.setStyleSheet(_fromUtf8(""))
        self.buttonMute.setFlat(False)
        self.buttonMute.setObjectName(_fromUtf8("buttonMute"))
        self.gridLayout.addWidget(self.buttonMute, 1, 3, 1, 1)
        self.buttonSeekBack = QtGui.QPushButton(self.widget)
        self.buttonSeekBack.setObjectName(_fromUtf8("buttonSeekBack"))
        self.gridLayout.addWidget(self.buttonSeekBack, 0, 1, 1, 1)
        self.buttonSeekForward = QtGui.QPushButton(self.widget)
        self.buttonSeekForward.setObjectName(_fromUtf8("buttonSeekForward"))
        self.gridLayout.addWidget(self.buttonSeekForward, 0, 3, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.pushButton_3 = QtGui.QPushButton(self.widget)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.horizontalLayout_4.addWidget(self.pushButton_3)
        self.pushButton = QtGui.QPushButton(self.widget)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout_4.addWidget(self.pushButton)
        self.buttonResetAll = QtGui.QPushButton(self.widget)
        self.buttonResetAll.setObjectName(_fromUtf8("buttonResetAll"))
        self.horizontalLayout_4.addWidget(self.buttonResetAll)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3.addWidget(self.widget)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.comboBoxTransformationType = QtGui.QComboBox(self.tab_2)
        self.comboBoxTransformationType.setObjectName(_fromUtf8("comboBoxTransformationType"))
        self.comboBoxTransformationType.addItem(_fromUtf8(""))
        self.comboBoxTransformationType.addItem(_fromUtf8(""))
        self.comboBoxTransformationType.addItem(_fromUtf8(""))
        self.comboBoxTransformationType.addItem(_fromUtf8(""))
        self.comboBoxTransformationType.addItem(_fromUtf8(""))
        self.verticalLayout.addWidget(self.comboBoxTransformationType)
        self.stackedWidget = QtGui.QStackedWidget(self.tab_2)
        self.stackedWidget.setFrameShape(QtGui.QFrame.NoFrame)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.page = QtGui.QWidget()
        self.page.setObjectName(_fromUtf8("page"))
        self.formLayout_2 = QtGui.QFormLayout(self.page)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.page_2)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.label_22 = QtGui.QLabel(self.page_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_22.setFont(font)
        self.label_22.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_8.addWidget(self.label_22, 0, 0, 1, 1)
        self.label_21 = QtGui.QLabel(self.page_2)
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_8.addWidget(self.label_21, 1, 0, 1, 1)
        self.comboBoxAspectRatioMatchingMode = QtGui.QComboBox(self.page_2)
        self.comboBoxAspectRatioMatchingMode.setObjectName(_fromUtf8("comboBoxAspectRatioMatchingMode"))
        self.comboBoxAspectRatioMatchingMode.addItem(_fromUtf8(""))
        self.comboBoxAspectRatioMatchingMode.addItem(_fromUtf8(""))
        self.gridLayout_8.addWidget(self.comboBoxAspectRatioMatchingMode, 1, 1, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_8)
        spacerItem1 = QtGui.QSpacerItem(20, 218, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem1)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtGui.QWidget()
        self.page_3.setObjectName(_fromUtf8("page_3"))
        self.gridLayout_5 = QtGui.QGridLayout(self.page_3)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem2, 3, 0, 1, 1)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.spinBoxSliceDuration = QtGui.QSpinBox(self.page_3)
        self.spinBoxSliceDuration.setMaximum(9000)
        self.spinBoxSliceDuration.setProperty("value", 120)
        self.spinBoxSliceDuration.setObjectName(_fromUtf8("spinBoxSliceDuration"))
        self.gridLayout_6.addWidget(self.spinBoxSliceDuration, 1, 1, 1, 1)
        self.spinBoxMaxSlicePerVideo = QtGui.QSpinBox(self.page_3)
        self.spinBoxMaxSlicePerVideo.setMinimum(1)
        self.spinBoxMaxSlicePerVideo.setMaximum(10000)
        self.spinBoxMaxSlicePerVideo.setProperty("value", 4)
        self.spinBoxMaxSlicePerVideo.setObjectName(_fromUtf8("spinBoxMaxSlicePerVideo"))
        self.gridLayout_6.addWidget(self.spinBoxMaxSlicePerVideo, 2, 1, 1, 1)
        self.label_14 = QtGui.QLabel(self.page_3)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_6.addWidget(self.label_14, 2, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.page_3)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_6.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.page_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_6.addWidget(self.label_3, 0, 0, 1, 1)
        self.comboBoxSliceDiscardMethod = QtGui.QComboBox(self.page_3)
        self.comboBoxSliceDiscardMethod.setObjectName(_fromUtf8("comboBoxSliceDiscardMethod"))
        self.comboBoxSliceDiscardMethod.addItem(_fromUtf8(""))
        self.comboBoxSliceDiscardMethod.addItem(_fromUtf8(""))
        self.comboBoxSliceDiscardMethod.addItem(_fromUtf8(""))
        self.gridLayout_6.addWidget(self.comboBoxSliceDiscardMethod, 3, 1, 1, 1)
        self.label_16 = QtGui.QLabel(self.page_3)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_6.addWidget(self.label_16, 3, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtGui.QWidget()
        self.page_4.setObjectName(_fromUtf8("page_4"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.page_4)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.doubleSpinBoxSuperCutCutDuration = QtGui.QDoubleSpinBox(self.page_4)
        self.doubleSpinBoxSuperCutCutDuration.setMinimum(0.0)
        self.doubleSpinBoxSuperCutCutDuration.setMaximum(60.0)
        self.doubleSpinBoxSuperCutCutDuration.setSingleStep(0.1)
        self.doubleSpinBoxSuperCutCutDuration.setProperty("value", 0.7)
        self.doubleSpinBoxSuperCutCutDuration.setObjectName(_fromUtf8("doubleSpinBoxSuperCutCutDuration"))
        self.gridLayout_7.addWidget(self.doubleSpinBoxSuperCutCutDuration, 1, 1, 1, 1)
        self.label_18 = QtGui.QLabel(self.page_4)
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_7.addWidget(self.label_18, 1, 0, 1, 1)
        self.label_17 = QtGui.QLabel(self.page_4)
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_7.addWidget(self.label_17, 2, 0, 1, 1)
        self.spinBoxSuperCutsPerFile = QtGui.QSpinBox(self.page_4)
        self.spinBoxSuperCutsPerFile.setMinimum(1)
        self.spinBoxSuperCutsPerFile.setMaximum(10000)
        self.spinBoxSuperCutsPerFile.setObjectName(_fromUtf8("spinBoxSuperCutsPerFile"))
        self.gridLayout_7.addWidget(self.spinBoxSuperCutsPerFile, 2, 1, 1, 1)
        self.label_19 = QtGui.QLabel(self.page_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_7.addWidget(self.label_19, 0, 0, 1, 1)
        self.comboBoxSuperCutFileNameStamp = QtGui.QComboBox(self.page_4)
        self.comboBoxSuperCutFileNameStamp.setObjectName(_fromUtf8("comboBoxSuperCutFileNameStamp"))
        self.comboBoxSuperCutFileNameStamp.addItem(_fromUtf8(""))
        self.comboBoxSuperCutFileNameStamp.addItem(_fromUtf8(""))
        self.comboBoxSuperCutFileNameStamp.addItem(_fromUtf8(""))
        self.gridLayout_7.addWidget(self.comboBoxSuperCutFileNameStamp, 4, 1, 1, 1)
        self.label_20 = QtGui.QLabel(self.page_4)
        self.label_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_7.addWidget(self.label_20, 4, 0, 1, 1)
        self.label_23 = QtGui.QLabel(self.page_4)
        self.label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_7.addWidget(self.label_23, 3, 0, 1, 1)
        self.comboBoxSuperCutAspectRatioMode = QtGui.QComboBox(self.page_4)
        self.comboBoxSuperCutAspectRatioMode.setObjectName(_fromUtf8("comboBoxSuperCutAspectRatioMode"))
        self.comboBoxSuperCutAspectRatioMode.addItem(_fromUtf8(""))
        self.comboBoxSuperCutAspectRatioMode.addItem(_fromUtf8(""))
        self.gridLayout_7.addWidget(self.comboBoxSuperCutAspectRatioMode, 3, 1, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_7)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem3)
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtGui.QWidget()
        self.page_5.setObjectName(_fromUtf8("page_5"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.page_5)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.gridLayout_9 = QtGui.QGridLayout()
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.comboBoxWallDurationMatching = QtGui.QComboBox(self.page_5)
        self.comboBoxWallDurationMatching.setObjectName(_fromUtf8("comboBoxWallDurationMatching"))
        self.comboBoxWallDurationMatching.addItem(_fromUtf8(""))
        self.comboBoxWallDurationMatching.addItem(_fromUtf8(""))
        self.comboBoxWallDurationMatching.addItem(_fromUtf8(""))
        self.gridLayout_9.addWidget(self.comboBoxWallDurationMatching, 3, 1, 1, 1)
        self.comboBoxWallAspectRatioMode = QtGui.QComboBox(self.page_5)
        self.comboBoxWallAspectRatioMode.setObjectName(_fromUtf8("comboBoxWallAspectRatioMode"))
        self.comboBoxWallAspectRatioMode.addItem(_fromUtf8(""))
        self.comboBoxWallAspectRatioMode.addItem(_fromUtf8(""))
        self.gridLayout_9.addWidget(self.comboBoxWallAspectRatioMode, 4, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.page_5)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_9.addWidget(self.label_4, 4, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.page_5)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_9.addWidget(self.label_5, 3, 0, 1, 1)
        self.label_25 = QtGui.QLabel(self.page_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_25.setFont(font)
        self.label_25.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_9.addWidget(self.label_25, 0, 0, 1, 1)
        self.spinBoxVideoWallWidth = QtGui.QSpinBox(self.page_5)
        self.spinBoxVideoWallWidth.setMinimum(1)
        self.spinBoxVideoWallWidth.setMaximum(99)
        self.spinBoxVideoWallWidth.setProperty("value", 4)
        self.spinBoxVideoWallWidth.setObjectName(_fromUtf8("spinBoxVideoWallWidth"))
        self.gridLayout_9.addWidget(self.spinBoxVideoWallWidth, 1, 1, 1, 1)
        self.label_24 = QtGui.QLabel(self.page_5)
        self.label_24.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_9.addWidget(self.label_24, 1, 0, 1, 1)
        self.label = QtGui.QLabel(self.page_5)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_9.addWidget(self.label, 2, 0, 1, 1)
        self.spinBoxVideoWallHeight = QtGui.QSpinBox(self.page_5)
        self.spinBoxVideoWallHeight.setMinimum(1)
        self.spinBoxVideoWallHeight.setProperty("value", 2)
        self.spinBoxVideoWallHeight.setObjectName(_fromUtf8("spinBoxVideoWallHeight"))
        self.gridLayout_9.addWidget(self.spinBoxVideoWallHeight, 2, 1, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout_9)
        spacerItem4 = QtGui.QSpacerItem(20, 140, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem4)
        self.stackedWidget.addWidget(self.page_5)
        self.verticalLayout.addWidget(self.stackedWidget)
        self.line = QtGui.QFrame(self.tab_2)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout.addWidget(self.line)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.comboBoxOutputFormat = QtGui.QComboBox(self.tab_2)
        self.comboBoxOutputFormat.setObjectName(_fromUtf8("comboBoxOutputFormat"))
        self.comboBoxOutputFormat.addItem(_fromUtf8(""))
        self.comboBoxOutputFormat.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.comboBoxOutputFormat, 4, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.tab_2)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_3.addWidget(self.label_11, 4, 0, 1, 1)
        self.label_12 = QtGui.QLabel(self.tab_2)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_3.addWidget(self.label_12, 2, 0, 1, 1)
        self.doubleSpinBoxBitRateKB = QtGui.QDoubleSpinBox(self.tab_2)
        self.doubleSpinBoxBitRateKB.setDecimals(2)
        self.doubleSpinBoxBitRateKB.setMinimum(50.0)
        self.doubleSpinBoxBitRateKB.setMaximum(4000.0)
        self.doubleSpinBoxBitRateKB.setSingleStep(100.0)
        self.doubleSpinBoxBitRateKB.setProperty("value", 1500.0)
        self.doubleSpinBoxBitRateKB.setObjectName(_fromUtf8("doubleSpinBoxBitRateKB"))
        self.gridLayout_3.addWidget(self.doubleSpinBoxBitRateKB, 2, 1, 1, 1)
        self.label_13 = QtGui.QLabel(self.tab_2)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_3.addWidget(self.label_13, 0, 0, 1, 1)
        self.comboBoxWidthMode = QtGui.QComboBox(self.tab_2)
        self.comboBoxWidthMode.setObjectName(_fromUtf8("comboBoxWidthMode"))
        self.comboBoxWidthMode.addItem(_fromUtf8(""))
        self.comboBoxWidthMode.addItem(_fromUtf8(""))
        self.comboBoxWidthMode.addItem(_fromUtf8(""))
        self.comboBoxWidthMode.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.comboBoxWidthMode, 1, 1, 1, 1)
        self.spinBoxOutputWidth = QtGui.QSpinBox(self.tab_2)
        self.spinBoxOutputWidth.setMaximum(7680)
        self.spinBoxOutputWidth.setProperty("value", 900)
        self.spinBoxOutputWidth.setObjectName(_fromUtf8("spinBoxOutputWidth"))
        self.gridLayout_3.addWidget(self.spinBoxOutputWidth, 0, 1, 1, 1)
        self.spinBoxFrameRate = QtGui.QSpinBox(self.tab_2)
        self.spinBoxFrameRate.setMinimum(1)
        self.spinBoxFrameRate.setMaximum(300)
        self.spinBoxFrameRate.setProperty("value", 24)
        self.spinBoxFrameRate.setObjectName(_fromUtf8("spinBoxFrameRate"))
        self.gridLayout_3.addWidget(self.spinBoxFrameRate, 3, 1, 1, 1)
        self.label_15 = QtGui.QLabel(self.tab_2)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_3.addWidget(self.label_15, 3, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.buttonProcess = QtGui.QPushButton(self.tab_3)
        self.buttonProcess.setObjectName(_fromUtf8("buttonProcess"))
        self.horizontalLayout_2.addWidget(self.buttonProcess)
        self.pushButton_2 = QtGui.QPushButton(self.tab_3)
        self.pushButton_2.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.labelProgress = QtGui.QLabel(self.tab_3)
        self.labelProgress.setWordWrap(True)
        self.labelProgress.setObjectName(_fromUtf8("labelProgress"))
        self.verticalLayout_2.addWidget(self.labelProgress)
        self.progressBar = QtGui.QProgressBar(self.tab_3)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.verticalLayout_2.addWidget(self.progressBar)
        self.plainTextEdit = QtGui.QPlainTextEdit(self.tab_3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monospace"))
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setMouseTracking(True)
        self.plainTextEdit.setStyleSheet(_fromUtf8("color:lime;background-color:black;"))
        self.plainTextEdit.setFrameShape(QtGui.QFrame.NoFrame)
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.plainTextEdit.setObjectName(_fromUtf8("plainTextEdit"))
        self.verticalLayout_2.addWidget(self.plainTextEdit)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.comboBoxTransformationType, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), self.stackedWidget.setCurrentIndex)
        QtCore.QObject.connect(self.stackedWidget, QtCore.SIGNAL(_fromUtf8("currentChanged(int)")), self.comboBoxTransformationType.setCurrentIndex)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "VideoNurd", None))
        self.buttonOpenFile.setText(_translate("MainWindow", "Import File(s)", None))
        self.buttonImportFolder.setText(_translate("MainWindow", "Import Folder", None))
        self.listWidgetFileListing.setSortingEnabled(False)
        self.buttonClearAll.setText(_translate("MainWindow", "Clear All", None))
        self.label_10.setText(_translate("MainWindow", "Right", None))
        self.label_9.setText(_translate("MainWindow", "Bottom", None))
        self.label_7.setText(_translate("MainWindow", "Top", None))
        self.label_8.setText(_translate("MainWindow", "Left", None))
        self.buttonABmode.setText(_translate("MainWindow", "A/B Mode", None))
        self.buttonPlayPause.setText(_translate("MainWindow", "Play/Pause", None))
        self.buttonSetStart.setText(_translate("MainWindow", "Set Start", None))
        self.buttonSetEnd.setText(_translate("MainWindow", "Set End", None))
        self.buttonMute.setText(_translate("MainWindow", "Mute", None))
        self.buttonSeekBack.setText(_translate("MainWindow", "<< Step", None))
        self.buttonSeekForward.setText(_translate("MainWindow", "Step >>", None))
        self.pushButton_3.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton.setText(_translate("MainWindow", "PushButton", None))
        self.buttonResetAll.setText(_translate("MainWindow", "Reset all options", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Sources", None))
        self.comboBoxTransformationType.setItemText(0, _translate("MainWindow", "Direct output - Each source file will be saved as a separate file", None))
        self.comboBoxTransformationType.setItemText(1, _translate("MainWindow", "Join - All source files will be joined into a single output file", None))
        self.comboBoxTransformationType.setItemText(2, _translate("MainWindow", "Slice - Each source file will be sliced into smaller files ", None))
        self.comboBoxTransformationType.setItemText(3, _translate("MainWindow", "SuperCut - Random extracts from all source files will be joined into montages", None))
        self.comboBoxTransformationType.setItemText(4, _translate("MainWindow", "VideoWall - Source clips will be joined into a grid.", None))
        self.label_22.setText(_translate("MainWindow", "Join Transformation", None))
        self.label_21.setText(_translate("MainWindow", "Aspect ratio matching mode", None))
        self.comboBoxAspectRatioMatchingMode.setItemText(0, _translate("MainWindow", "Crop edges of video to fit cell aspect ratio", None))
        self.comboBoxAspectRatioMatchingMode.setItemText(1, _translate("MainWindow", "Add letterbox around clip to fit aspect ratio", None))
        self.spinBoxSliceDuration.setSuffix(_translate("MainWindow", " seconds", None))
        self.label_14.setText(_translate("MainWindow", "Maximum slice count per source video", None))
        self.label_2.setText(_translate("MainWindow", "Maximum slice duration", None))
        self.label_3.setText(_translate("MainWindow", "Slice Transformation", None))
        self.comboBoxSliceDiscardMethod.setItemText(0, _translate("MainWindow", "Choose slices at random", None))
        self.comboBoxSliceDiscardMethod.setItemText(1, _translate("MainWindow", "Prefer slices from the start of each clip", None))
        self.comboBoxSliceDiscardMethod.setItemText(2, _translate("MainWindow", "Prefer slices from the end of each clip", None))
        self.label_16.setText(_translate("MainWindow", "Slice discard method", None))
        self.doubleSpinBoxSuperCutCutDuration.setSuffix(_translate("MainWindow", " seconds", None))
        self.label_18.setText(_translate("MainWindow", "Cut duration", None))
        self.label_17.setText(_translate("MainWindow", "Cuts to extract per file", None))
        self.label_19.setText(_translate("MainWindow", "SuperCut Transformation", None))
        self.comboBoxSuperCutFileNameStamp.setItemText(0, _translate("MainWindow", "No filename stamps", None))
        self.comboBoxSuperCutFileNameStamp.setItemText(1, _translate("MainWindow", "Stamp with filename at top", None))
        self.comboBoxSuperCutFileNameStamp.setItemText(2, _translate("MainWindow", "Stamp with filename at bottom", None))
        self.label_20.setText(_translate("MainWindow", "Stamp filenames on clips", None))
        self.label_23.setText(_translate("MainWindow", "TextLabel", None))
        self.comboBoxSuperCutAspectRatioMode.setItemText(0, _translate("MainWindow", "Crop edges of video to fit cell aspect ratio", None))
        self.comboBoxSuperCutAspectRatioMode.setItemText(1, _translate("MainWindow", "Add letterbox around clip to fit aspect ratio", None))
        self.comboBoxWallDurationMatching.setItemText(0, _translate("MainWindow", "Limit the output to the length of the shortest clip", None))
        self.comboBoxWallDurationMatching.setItemText(1, _translate("MainWindow", "Show blank cell at the start of short clips (Synchronise by end time)", None))
        self.comboBoxWallDurationMatching.setItemText(2, _translate("MainWindow", "Show blank cell at the end of short clips (Synchronise by start time)", None))
        self.comboBoxWallAspectRatioMode.setItemText(0, _translate("MainWindow", "Crop edges of video to fit cell aspect ratio", None))
        self.comboBoxWallAspectRatioMode.setItemText(1, _translate("MainWindow", "Add letterbox around clip to fit aspect ratio", None))
        self.label_4.setText(_translate("MainWindow", "Aspect ratio matching mode", None))
        self.label_5.setText(_translate("MainWindow", "Duration matching mode", None))
        self.label_25.setText(_translate("MainWindow", "VideoWall Transformation", None))
        self.spinBoxVideoWallWidth.setSuffix(_translate("MainWindow", " cells", None))
        self.label_24.setText(_translate("MainWindow", "Grid width", None))
        self.label.setText(_translate("MainWindow", "Grid height", None))
        self.spinBoxVideoWallHeight.setSuffix(_translate("MainWindow", " cells", None))
        self.comboBoxOutputFormat.setItemText(0, _translate("MainWindow", ".webm", None))
        self.comboBoxOutputFormat.setItemText(1, _translate("MainWindow", ".mp4", None))
        self.label_11.setText(_translate("MainWindow", "Output Format", None))
        self.label_12.setText(_translate("MainWindow", "Output Bitrate", None))
        self.doubleSpinBoxBitRateKB.setSuffix(_translate("MainWindow", " Kb/s", None))
        self.label_13.setText(_translate("MainWindow", "Output Width", None))
        self.comboBoxWidthMode.setItemText(0, _translate("MainWindow", "Only Shrink", None))
        self.comboBoxWidthMode.setItemText(1, _translate("MainWindow", "Only Enlarge", None))
        self.comboBoxWidthMode.setItemText(2, _translate("MainWindow", "Always Resize", None))
        self.comboBoxWidthMode.setItemText(3, _translate("MainWindow", "Never Resize", None))
        self.spinBoxOutputWidth.setSuffix(_translate("MainWindow", " px", None))
        self.spinBoxFrameRate.setSuffix(_translate("MainWindow", " fps", None))
        self.label_15.setText(_translate("MainWindow", "Ouput Framerate", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Transformations", None))
        self.buttonProcess.setText(_translate("MainWindow", "Start Processing", None))
        self.pushButton_2.setText(_translate("MainWindow", "Stop", None))
        self.labelProgress.setText(_translate("MainWindow", "Converter Status: Idle", None))
        self.plainTextEdit.setPlainText(_translate("MainWindow", "########################################################\n"
"#                                                      #\n"
"#   VideoNurd beta - A gui wrapper over moviepy        #\n"
"#                                                      #\n"
"#   Made with love for the freaks at /webm/ and /wx/   #\n"
"#                                                      #\n"
"########################################################", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Progress", None))

